import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = path.resolve(root, '../output');
await fs.mkdir(output, { recursive: true });
const text = `SEU PRÓPRIO CHEFE? — MOTORISTA POR UM DIA EM BH\n\nJOGAR AGORA\nhttp://localhost:4173\n\nSEM INTERNET\nAbra ${path.join(output, 'JOGAR-SEM-INTERNET.html')} no Chrome ou Edge. O arquivo contém o jogo completo.\n\nNA AULA\nClique em Jogar com a turma. Ouça a sala e escolha horário, tempo sem corrida e quilômetros. Cada clique avança. No resultado, leia entrou, custos e ficou. Use Usar meus valores para colocar os dados reais do motorista. Depois, explore Autonomia, Tempo, Custos e Proteção.\n\nREFERÊNCIAS\nGasolina de BH: R$ 6,42/l, ANP, 27/09 a 03/10/2026. Consumo do Onix MT 1.0: 13,5 km/l, Inmetro. Ganhos iniciais: R$ 47 por hora em viagem, Cebrap/Amobitec, dados nacionais de maio/2023 a abril/2024. Esta referência histórica não é tarifa atual da Uber. Outros custos precisam ser informados; o resultado inicial é após gasolina. Detalhes em FONTES-DOS-VALORES.md e no botão Fontes.\n\nPUBLICAR\nRepositório: https://github.com/Lucasmagdev/uberiza-o\nConecte-o ao Netlify ou envie ${path.join(output, 'seu-proprio-chefe-netlify.zip')} pelo Netlify Drop. Os antigos links de publicação temporária são da versão anterior.\n\nINICIAR LOCALMENTE\nNa pasta app, execute npm start ou powershell -NoProfile -ExecutionPolicy Bypass -File scripts/start-local.ps1.\n`;
await fs.writeFile(path.join(output, 'ACESSO-AO-JOGO.txt'), text, 'utf8');
await fs.writeFile(path.join(output, 'ABRIR-JOGO-LOCAL.url'), '[InternetShortcut]\nURL=http://localhost:4173\n', 'utf8');
console.log(JSON.stringify({ guide: path.join(output, 'ACESSO-AO-JOGO.txt'), offline: path.join(output, 'JOGAR-SEM-INTERNET.html') }));
