import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = path.resolve(root, '../output');
const deployment = JSON.parse(await fs.readFile(path.join(root, '.netlify/deployment.json'), 'utf8'));
const url = deployment.site_url.replace(/^http:/, 'https:');
const jwt = new URL(deployment.claim_url).hash.split('drop_token=')[1];
const expires = jwt ? JSON.parse(Buffer.from(jwt.split('.')[1], 'base64url').toString()).exp : null;
const expiry = expires ? new Date(expires * 1000).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' }) : 'uma hora após a publicação';
const text = `SEU PRÓPRIO CHEFE? — APP PRONTO\n\nLINK NO NETLIFY\n${url}\n\nSENHA DA PUBLICAÇÃO TEMPORÁRIA\n${deployment.password || 'Sem senha'}\n\nMANTER O LINK ONLINE\nReivindique esta publicação na sua conta Netlify antes de ${expiry} (horário de São Paulo):\n${deployment.claim_url}\n\nA publicação foi feita sem uma sessão autenticada e o Netlify remove projetos não reivindicados após uma hora. Essa senha é a proteção criada pelo próprio Netlify para a publicação temporária.\n\nVERSÃO LOCAL JÁ RODANDO\nhttp://localhost:4173\n\nPARA A AULA\nAbra o jogo e escolha “Conduzir com a turma”. Projete em tela cheia, peça a votação inicial por mãos levantadas e registre os totais. A turma decide em voz alta; você confirma as quatro escolhas. No resultado, compare custos, horas e proteção e explore as provocações. Termine com a segunda votação.\n\nCada celular também pode jogar individualmente. As partidas são independentes; as respostas da turma são registradas manualmente no computador do apresentador.\n\nCÓDIGO E PACOTE\nCódigo: ${root}\nPacote pronto para enviar ao Netlify Drop: ${path.join(output, 'seu-proprio-chefe-netlify.zip')}\n\nSe o link temporário expirar, a versão local e o pacote continuam disponíveis. Para ligar o app local novamente, execute npm start na pasta app.\n\nVALIDAÇÃO\nOs testes verificam as 24 combinações de decisões, as contas de tempo e dinheiro, partida individual, modo turma, votação antes/depois, mudança de escolhas, recarregamento, tela cheia, teclado e telas de 320, 390 e 1920 pixels.\n\nCONTEÚDO\nValores fictícios e regras visíveis. Base conceitual: Abílio, Amorim e Grohmann (2021), DOI https://doi.org/10.1590/15174522-116484.\n`;
const offlineGuide = `\nJOGAR SEM INTERNET — RECOMENDADO COMO RESERVA PARA A AULA\nAbra ${path.join(output, 'JOGAR-SEM-INTERNET.html')} no Chrome ou Edge. Não precisa de servidor, instalação ou conexão. Essa cópia contém a mesma partida individual e o mesmo modo turma da publicação online.\n\nMELHORIAS VERIFICADAS\nLetras maiores no modo turma; teclas pressionadas não pulam etapas; confirmação ao reiniciar pelo logo; controles acessíveis no celular; aviso quando o navegador não consegue guardar o progresso; endereço selecionável quando a cópia automática é bloqueada.\n\nA versão offline completou partidas individual e coletiva, votação antes/depois, compartilhamento e recarregamento com a internet desligada e sem fazer conexões de rede.\n\nINICIAR O SERVIDOR LOCAL NO WINDOWS\nAbra o PowerShell na pasta app e execute:\n  powershell -NoProfile -ExecutionPolicy Bypass -File scripts/start-local.ps1\nO comando verifica se o app já está ligado e só confirma o início depois que ele responder.\n`;
await fs.writeFile(path.join(output, 'ACESSO-AO-JOGO.txt'), text + offlineGuide, 'utf8');
await fs.writeFile(path.join(output, 'ABRIR-JOGO-LOCAL.url'), '[InternetShortcut]\nURL=http://localhost:4173\n', 'utf8');
await fs.writeFile(path.join(output, 'ABRIR-JOGO-NETLIFY.url'), `[InternetShortcut]\nURL=${url}\n`, 'utf8');
await fs.writeFile(path.join(output, 'REIVINDICAR-NO-NETLIFY.url'), `[InternetShortcut]\nURL=${deployment.claim_url}\n`, 'utf8');
console.log(JSON.stringify({ publicUrl: url, accessGuide: path.join(output, 'ACESSO-AO-JOGO.txt'), temporaryUntil: expiry }));
